# Generated by Django 2.1.7 on 2019-03-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACRBlockchain', '0002_customuser_is_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_student',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ratee'), (2, 'IO'), (3, 'RO'), (4, 'SRO'), (5, 'AO'), (6, 'Admin'), (7, 'Clerk')], default=1),
        ),
    ]
